services:
  mongodb:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/authdb
      JWT_SECRET: ${JWT_SECRET:-Z7L+U7qZ7hem3u9IsLs+fpb0uiO4viiFY5P7cXiIXLk=}
    depends_on:
      mongodb:
        condition: service_healthy

  course-service:
    build: ./course-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/coursedb
      JWT_SECRET: ${JWT_SECRET:-Z7L+U7qZ7hem3u9IsLs+fpb0uiO4viiFY5P7cXiIXLk=}
    depends_on:
      mongodb:
        condition: service_healthy

  api-gateway:
    build: ./api-gateway
    ports:
      - "8085:8085"
    environment:
      JWT_SECRET: ${JWT_SECRET:-Z7L+U7qZ7hem3u9IsLs+fpb0uiO4viiFY5P7cXiIXLk=}
      AUTH_SERVICE_URL: http://auth-service:8081
      COURSE_SERVICE_URL: http://course-service:8082
    depends_on:
      - auth-service
      - course-service

volumes:
  mongo-data:
