spring.application.name=api-gateway

server.port=8085

security.jwt.secret=${JWT_SECRET:Z7L+U7qZ7hem3u9IsLs+fpb0uiO4viiFY5P7cXiIXLk=}
logging.structured.format.console=ecs

gateway.auth-service.url=${AUTH_SERVICE_URL:http://localhost:8081}
gateway.course-service.url=${COURSE_SERVICE_URL:http://localhost:8082}

#spring.cloud.gateway.server.webmvc.routes[0].id=auth
#spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
#spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**
#
#spring.cloud.gateway.server.webmvc.routes[1].id=courses
#spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
#spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/courses/**,/me/**,/debug/**

