apiVersion: v1
kind: ResourceQuota
metadata:
  name: lms-memory-guardrail
  namespace: lms
spec:
  hard:
    requests.cpu: "200m"
    limits.cpu: "800m"
    requests.memory: "280Mi"
    limits.memory: "520Mi"
    pods: "5"
