apiVersion: v1
kind: ResourceQuota
metadata:
  name: lms-memory-guardrail
  namespace: lms
spec:
  hard:
    requests.cpu: "1000m"
    limits.cpu: "2000m"
    requests.memory: "1Gi"
    limits.memory: "3Gi"
    pods: "10"
