apiVersion: v1
kind: Secret
metadata:
  name: lms-secrets
  namespace: lms
type: Opaque
stringData:
  JWT_SECRET: "<set-in-cluster-or-ci>"
  AUTH_MONGODB_URI: "<set-in-cluster-or-ci>"
  COURSE_MONGODB_URI: "<set-in-cluster-or-ci>"
