apiVersion: v1
kind: Secret
metadata:
  name: lms-secrets
  namespace: lms
type: Opaque
stringData:
  JWT_SECRET: "Z7L+U7qZ7hem3u9IsLs+fpb0uiO4viiFY5P7cXiIXLk="
  AUTH_MONGODB_URI: "mongodb://mongodb:27017/authdb"
  COURSE_MONGODB_URI: "mongodb://mongodb:27017/coursedb"
