apiVersion: v1
kind: Secret
metadata:
  name: lms-secrets
  namespace: lms
type: Opaque
stringData:
  JWT_SECRET: "REMOVED_JWT_SECRET="
  AUTH_MONGODB_URI: "mongodb://mongodb:27017/authdb"
  COURSE_MONGODB_URI: "mongodb://mongodb:27017/coursedb"
