apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: lms/api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: lms-secrets
                  key: JWT_SECRET
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:8081"
            - name: COURSE_SERVICE_URL
              value: "http://course-service:8082"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
